# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('opersys', models.CharField(blank=True, default=None, max_length=16)),
                ('client_version', models.IntegerField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WinEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_name', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=32)),
                ('event_id', models.CharField(max_length=16)),
                ('level', models.CharField(max_length=16)),
                ('user', models.CharField(blank=True, max_length=32)),
                ('opcode', models.CharField(blank=True, max_length=16)),
                ('description', models.TextField(blank=True)),
                ('logged', models.DateTimeField()),
                ('task_category', models.CharField(blank=True, max_length=16)),
                ('keywords', models.CharField(blank=True, max_length=16)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winevent.Computer')),
            ],
        ),
    ]
