# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winevent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winevent',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='winevent',
            name='logged',
        ),
        migrations.RemoveField(
            model_name='winevent',
            name='opcode',
        ),
        migrations.RemoveField(
            model_name='winevent',
            name='task_category',
        ),
    ]
