# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winevent', '0002_auto_20170618_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='wmi_warning',
            field=models.BooleanField(default=False),
        ),
    ]
